name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: Setup ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0
          #              ^^^^^^

      - name: Build
        run: |
          opam install dune
          opam install . --deps-only 
          eval $(opam env)
          mkdir dist
          dune exec tools/bin/main.exe 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
