name: Check pull requests

on:
  pull_request

jobs:
  check_pr:
    runs-on: ubuntu-18.04
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Setup ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0
          #              ^^^^^^

      - name: Build
        run: |
          opam install dune core cmdliner yojson jingoo ppx_deriving
          eval $(opam env)
          dune exec tools/bin/main.exe 
